# Generated by Django 3.2.5 on 2021-07-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pais', models.CharField(max_length=25, verbose_name='País')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('codigo_postal', models.IntegerField(verbose_name='CodigoPostal')),
                ('habitaciones', models.IntegerField(verbose_name='Habitaciones')),
            ],
        ),
    ]
