# Generated by Django 3.2.5 on 2021-07-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre País')),
                ('codigo_area', models.IntegerField(verbose_name='Código Área')),
            ],
        ),
    ]
