# Generated by Django 3.2.5 on 2021-07-28 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.IntegerField(verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nit', models.CharField(default='C/F', max_length=9, verbose_name='NIT')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('correo_electronico', models.EmailField(max_length=80, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Habitacion',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre del Tipo Habitación')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fecha', models.DateField(verbose_name='Fecha de Reservación')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.cliente', verbose_name='Cliente')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.hotel', verbose_name='Hotel')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Decimal')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.hotel', verbose_name='Hotel')),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.tipo_habitacion', verbose_name='Tipo')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('no_serie', models.CharField(max_length=15, verbose_name='No. Serie')),
                ('fecha', models.DateField(verbose_name='Fecha de la Factura')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('reservacion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.reservacion', verbose_name='Reservación')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Reservacion',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('nombre_reservacion', models.CharField(max_length=60, verbose_name='Nombre de la Reservación')),
                ('habitacion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.habitacion', verbose_name='Habitación')),
                ('reservacion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.reservacion', verbose_name='Reservación')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Ciudad')),
                ('pais_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.pais', verbose_name='País')),
            ],
        ),
    ]
