# Generated by Django 3.2.5 on 2021-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_categoria_ciudad_cliente_detalle_reservacion_factura_habitacion_reservacion_tipo_habitacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='detalle_reservacion',
            options={'verbose_name_plural': 'Detalles de Reservaciones'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipo_habitacion',
            options={'verbose_name_plural': 'Tipo de Habitaciones'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=80, null=True, verbose_name='Correo Electronico'),
        ),
    ]
