# Generated by Django 3.2.5 on 2021-07-29 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0004_auto_20210728_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='habitaciones',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pais',
        ),
        migrations.AddField(
            model_name='hotel',
            name='categoria_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ciudad_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='usuario_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(default=None, max_length=80, null=True, verbose_name='Correo Electronico'),
        ),
    ]
