# Generated by Django 3.2.5 on 2021-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20210729_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_reservacion',
            options={'verbose_name': 'Detalle de Reservación', 'verbose_name_plural': 'Detalles de Reservaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipo_habitacion',
            options={'verbose_name': 'Tipo de Habitación', 'verbose_name_plural': 'Tipo de Habitaciones'},
        ),
        migrations.AddField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(blank=True, default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='tipo_habitacion',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Tipo Habitación'),
        ),
    ]
