# Generated by Django 3.2.5 on 2021-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210803_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('R', 'Reservado'), ('I', 'Inactivo')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numero_habitacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Habitación'),
        ),
    ]
