# Generated by Django 3.2.5 on 2021-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20210812_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('R', 'Reservado'), ('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('R', 'Reservado'), ('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
