# Generated by Django 3.2.5 on 2021-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20210816_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('N', 'No disponible'), ('R', 'Reservado'), ('D', 'Disponible')], default='D', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('N', 'No disponible'), ('R', 'Reservado'), ('D', 'Disponible')], default='D', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
