# Generated by Django 3.2.5 on 2021-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20210817_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('C', 'Cancela'), ('A', 'Actica'), ('P', 'Pagada')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
