# Generated by Django 3.2.6 on 2021-08-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20210817_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('N', 'No disponible'), ('D', 'Disponible'), ('R', 'Reservado')], default='D', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('C', 'Cancelada'), ('P', 'Pagada'), ('A', 'Activa')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
