# Generated by Django 3.2.6 on 2021-08-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20210824_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='no_serie',
            field=models.CharField(default='A', max_length=15, verbose_name='No. Serie'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('C', 'Cancelada'), ('A', 'Activa'), ('P', 'Pagada')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
