# Generated by Django 3.2.6 on 2021-08-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20210824_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('R', 'Reservado'), ('N', 'No disponible'), ('D', 'Disponible')], default='D', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activa'), ('C', 'Cancelada'), ('P', 'Pagada')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
